# Generated by Django 3.2.14 on 2024-09-03 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import formapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField(verbose_name='Заказчик')),
                ('project_dogovor', models.TextField(verbose_name='Договор №')),
                ('project_date_contract', models.DateField(blank=True, verbose_name='Дата договора')),
                ('project_name', models.TextField(verbose_name='Наименование договора')),
                ('project_reviewer', models.TextField(verbose_name='Рецензент')),
                ('out_mail_num', models.TextField(verbose_name='Письмо исх. №')),
                ('out_mail_date', models.DateField(blank=True, verbose_name='Письмо исх. дата')),
                ('in_mail_num', models.TextField(verbose_name='Письмо вх. №')),
                ('in_mail_date', models.DateField(blank=True, verbose_name='Письмо вх. дата')),
                ('num_reestr', models.TextField(verbose_name='Реестр №')),
                ('start_date', models.DateField(verbose_name='Дата создания')),
                ('end_date', models.DateField(verbose_name='Срок')),
                ('status', models.TextField(choices=[('Формирование', 'Формирование'), ('На заполнении', 'На заполнении'), ('На заполнении ГИПом', 'На заполнении ГИПом'), ('На заполнении руководителем', 'На заполнении руководителем'), ('На заполнении исполнителем', 'На заполнении исполнителем'), ('На согласовании руководителем', 'На согласовании руководителем'), ('На согласовании ГИПом', 'На согласовании ГИПом'), ('На согласовании', 'На согласовании'), ('На доработке', 'На доработке'), ('На доработке руководителем', 'На доработке руководителем'), ('На доработке исполнителем', 'На доработке исполнителем'), ('Согласовано ГИПом', 'Согласовано ГИПом'), ('Подготовка ответов', 'Подготовка ответов'), ('Подготовка ответов ГИПом', 'Подготовка ответов ГИПом'), ('Подготовка ответов руководителем', 'Подготовка ответов руководителем'), ('Подготовка ответов исполнителем', 'Подготовка ответов исполнителем'), ('Принято ГИПом', 'Принято ГИПом'), ('На согласовании Рецензентом', 'На согласовании Рецензентом'), ('Замечание снято', 'Замечание снято'), ('Закрыт', 'Закрыт')], default='Формирование', verbose_name='Статус')),
                ('gip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gip_set1', to=settings.AUTH_USER_MODEL, verbose_name='ГИП')),
            ],
            options={
                'verbose_name': 'реестр',
                'verbose_name_plural': 'Реестры',
            },
        ),
        migrations.CreateModel(
            name='reestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuality', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('status', models.TextField(choices=[('Формирование', 'Формирование'), ('На заполнении', 'На заполнении'), ('На заполнении ГИПом', 'На заполнении ГИПом'), ('На заполнении руководителем', 'На заполнении руководителем'), ('На заполнении исполнителем', 'На заполнении исполнителем'), ('На согласовании руководителем', 'На согласовании руководителем'), ('На согласовании ГИПом', 'На согласовании ГИПом'), ('На согласовании', 'На согласовании'), ('На доработке', 'На доработке'), ('На доработке руководителем', 'На доработке руководителем'), ('На доработке исполнителем', 'На доработке исполнителем'), ('Согласовано ГИПом', 'Согласовано ГИПом'), ('Подготовка ответов', 'Подготовка ответов'), ('Подготовка ответов ГИПом', 'Подготовка ответов ГИПом'), ('Подготовка ответов руководителем', 'Подготовка ответов руководителем'), ('Подготовка ответов исполнителем', 'Подготовка ответов исполнителем'), ('Принято ГИПом', 'Принято ГИПом'), ('На согласовании Рецензентом', 'На согласовании Рецензентом'), ('Замечание снято', 'Замечание снято'), ('Закрыт', 'Закрыт')], default='Формирование', verbose_name='Статус')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Срок исполнения текущего статуса')),
                ('customer', models.TextField(verbose_name='Заказчик')),
                ('project_dogovor', models.TextField(verbose_name='Договор №')),
                ('project_date_contract', models.DateField(blank=True, verbose_name='Дата договора')),
                ('project_name', models.TextField(verbose_name='Наименование договора')),
                ('project_reviewer', models.TextField(verbose_name='Рецензент')),
                ('out_mail_num', models.TextField(verbose_name='Письмо исх. №')),
                ('out_mail_date', models.DateField(blank=True, verbose_name='Письмо исх. дата')),
                ('in_mail_num', models.TextField(verbose_name='Письмо вх. №')),
                ('in_mail_date', models.DateField(blank=True, verbose_name='Письмо вх. дата')),
                ('num_reestr', models.TextField(verbose_name='Реестр №')),
                ('num_remark', models.TextField(verbose_name='1.1. № Замечания')),
                ('remark_v', models.IntegerField(verbose_name='1.2. Версия замечания')),
                ('remark_name', models.TextField(verbose_name='2. Наименование замечания')),
                ('rational', models.TextField(verbose_name='2.1. Обоснование')),
                ('designation_name', models.TextField(verbose_name='3. Обозначение раздела в проекте')),
                ('section_name', models.TextField(verbose_name='4. Наименование раздела')),
                ('answer_date_plan', models.DateField(blank=True, null=True, verbose_name='7. Дата предоставления ответов на замечания (План)')),
                ('answer_deadline_correct_plan', models.DateField(blank=True, null=True, verbose_name='9. Срок внесения корректировок (План)')),
                ('labor_costs_plan', models.FloatField(blank=True, null=True, verbose_name='10.1 Трудозатраты, дн. (на устранение замечания) (План)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='10.3. Комментарии')),
                ('answer_remark', models.TextField(blank=True, null=True, verbose_name='11. Ответы на замечания')),
                ('total_importance', models.TextField(blank=True, null=True, verbose_name='14. Значимость замечания')),
                ('root_cause_list', models.TextField(blank=True, null=True, verbose_name='15. Коренная причина')),
                ('root_cause_text', models.TextField(blank=True, null=True, verbose_name='Формулировка коренной причины')),
                ('link_tech_name', models.TextField(blank=True, null=True, verbose_name='12. Ссылка  в  технической документации')),
                ('cancel_remark', models.TextField(blank=True, null=True, verbose_name='13. Отметка о снятии замечания')),
                ('cancel_remark_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('answer_date_fact', models.DateField(blank=True, null=True, verbose_name='8. Дата предоставления ответов на замечания (Факт)')),
                ('answer_deadline_correct_fact', models.DateField(blank=True, null=True, verbose_name='10. Срок внесения корректировок (Факт)')),
                ('labor_costs_fact', models.FloatField(blank=True, null=True, verbose_name='10.2. Трудозатраты, дн. (на устранение замечания) (Факт)')),
                ('executor_fail_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executFail_set', to=settings.AUTH_USER_MODEL, verbose_name='6. Исполнитель, допустивший замечание')),
                ('executor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execut_set', to=settings.AUTH_USER_MODEL, verbose_name='6.1. Исполнитель, ответственный за устранение замечания')),
                ('gip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gip_set', to=settings.AUTH_USER_MODEL, verbose_name='ГИП')),
                ('reestrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.reestinfo', verbose_name='ID реестра')),
                ('responsibleTrouble_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsTroble_set', to=settings.AUTH_USER_MODEL, verbose_name='5. Ответственный за устранение замечаний (начальник подразделения)')),
            ],
            options={
                'verbose_name': 'замечание',
                'verbose_name_plural': 'Замечания',
            },
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_to', models.TextField(verbose_name='Принадлежность')),
                ('file', models.FileField(blank=True, null=True, upload_to=formapp.models.user_directory_path, verbose_name='Файл')),
                ('file_name', models.TextField(blank=True, null=True, verbose_name='Наименование документа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('file_size', models.TextField(blank=True, null=True, verbose_name='Размер файла')),
                ('upload_date', models.DateField(verbose_name='Дата загрузки')),
                ('reestr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.reestinfo', verbose_name='ID реестра')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
