# Generated by Django 3.2.14 on 2024-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr',
            name='executor_fail_text',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО исполнителя'),
        ),
    ]
