# Generated by Django 3.2.14 on 2024-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20240917_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr',
            name='root_cause_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Формулировка коренной причины'),
        ),
    ]
