# Generated by Django 3.2.14 on 2024-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_reestr_root_cause_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='root_cause_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
