# Generated by Django 3.2.14 on 2024-09-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_reestr_root_cause_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование краткое')),
            ],
            options={
                'verbose_name': 'заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='№ договора')),
                ('name', models.TextField(verbose_name='Наименование договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.customers', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
