# Generated by Django 3.2.14 on 2024-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_contracts_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'рецензент',
                'verbose_name_plural': 'Рецензенты',
            },
        ),
    ]
