# Generated by Django 3.2.14 on 2024-09-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestinfo',
            name='contractID',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='formapp.contracts', verbose_name='ID договора'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='customer',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.CASCADE, to='formapp.customers', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='project_reviewer',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.CASCADE, to='formapp.reviewers', verbose_name='Рецензент'),
        ),
    ]
