# Generated by Django 3.2.14 on 2024-09-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20240924_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reestinfo',
            name='contractID',
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='project_dogovor',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='formapp.contracts', verbose_name='ID договора'),
        ),
    ]
