# Generated by Django 3.2.14 on 2024-09-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_auto_20240924_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestinfo',
            name='project_dogovor',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='formapp.contracts', verbose_name='Договор №'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.customers', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='project_dogovor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.contracts', verbose_name='Договор №'),
        ),
    ]
