# Generated by Django 3.2.14 on 2024-09-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_auto_20240925_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='project_reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.reviewers', verbose_name='Рецензент'),
        ),
    ]
