# Generated by Django 3.2.14 on 2024-12-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_alter_reestr_project_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestinfo',
            name='in_mail_date',
            field=models.DateField(verbose_name='Письмо вх. дата'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='out_mail_date',
            field=models.DateField(verbose_name='Письмо исх. дата'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='project_date_contract',
            field=models.DateField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='root_cause_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к коренной причине'),
        ),
    ]
