# Generated by Django 3.2.14 on 2024-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_auto_20241226_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr',
            name='imp4_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите подразделения'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='imp7_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите, какие исходные данные требуются от Заказчика'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нарушены требования ЗНП и (или) обязательные требования нормативных документов'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Корректировка документации (свой раздел, глава, том, книга, др. док.)'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Корректировка смежных разделов (глав, томов, др. док.)'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выдача задания смежным подразделениям (без учёта ОКиВД) и (или) получение исходных данных от них'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Корректировка принятых проектных решений'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Корректировка принятых проектных решений требуется по причине'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='importance7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Получение дополнительных исходных данных от Заказчика'),
        ),
    ]
