# Generated by Django 3.2.14 on 2024-12-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_auto_20241226_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='importance1',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Нарушены требования ЗНП и (или) обязательные требования нормативных документов'),
        ),
    ]
