# Generated by Django 3.2.14 on 2024-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_alter_reestr_importance1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='importance2',
            field=models.BooleanField(blank=True, choices=[(True, 'Требуется'), (False, 'Не требуется')], default=None, null=True, verbose_name='Корректировка документации (свой раздел, глава, том, книга, др. док.)'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance3',
            field=models.BooleanField(blank=True, choices=[(True, 'Требуется'), (False, 'Не требуется')], default=None, null=True, verbose_name='Корректировка смежных разделов (глав, томов, др. док.)'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance4',
            field=models.BooleanField(blank=True, choices=[(True, 'Требуется'), (False, 'Не требуется')], default=None, null=True, verbose_name='Выдача задания смежным подразделениям (без учёта ОКиВД) и (или) получение исходных данных от них'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance5',
            field=models.BooleanField(blank=True, choices=[(True, 'Требуется'), (False, 'Не требуется')], default=None, null=True, verbose_name='Корректировка принятых проектных решений'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance6',
            field=models.BooleanField(blank=True, choices=[(True, 'Вина/Инициатива Заказчика'), (False, 'Вина проектировщика')], default=None, null=True, verbose_name='Корректировка принятых проектных решений требуется по причине'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance7',
            field=models.BooleanField(blank=True, choices=[(True, 'Требуется'), (False, 'Не требуется')], default=None, null=True, verbose_name='Получение дополнительных исходных данных от Заказчика'),
        ),
    ]
