# Generated by Django 3.2.14 on 2024-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0016_auto_20241226_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr',
            name='imp3_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите разделы (главы, тома, др. док.)'),
        ),
    ]
