# Generated by Django 3.2.14 on 2024-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_auto_20241227_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='importance1',
            field=models.BooleanField(blank=True, choices=[(None, '-----'), (True, 'Да'), (False, 'Нет')], default=None, null=True, verbose_name='Нарушены требования ЗНП и (или) обязательные требования нормативных документов'),
        ),
    ]
