# Generated by Django 3.2.14 on 2024-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0020_alter_reestr_importance1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='importance1',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Нарушены требования ЗНП и (или) обязательные требования нормативных документов'),
        ),
    ]
