# Generated by Django 3.2.14 on 2025-01-09 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formapp', '0021_alter_reestr_importance1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr',
            name='importance2',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Требуется корректировка документации (свой раздел, глава, том, книга, др. док.)'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance3',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Требуется корректировка смежных разделов (глав, томов, др. док.)'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance4',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Требуется выдача задания смежным подразделениям (без учёта ОКиВД) и (или) получение исходных данных от них'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance5',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Требуется корректировка принятых проектных решений'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance6',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Корректировка принятых проектных решений требуется по вине/инициативе Заказчика'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='importance7',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Требуется получение дополнительных исходных данных от Заказчика'),
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(choices=[('Формирование', 'Формирование'), ('На заполнении', 'На заполнении'), ('На заполнении ГИПом', 'На заполнении ГИПом'), ('На заполнении руководителем', 'На заполнении руководителем'), ('На заполнении исполнителем', 'На заполнении исполнителем'), ('На согласовании руководителем', 'На согласовании руководителем'), ('На согласовании ГИПом', 'На согласовании ГИПом'), ('На согласовании', 'На согласовании'), ('На доработке', 'На доработке'), ('На доработке ГИПом', 'На доработке ГИПом'), ('На доработке руководителем', 'На доработке руководителем'), ('На доработке исполнителем', 'На доработке исполнителем'), ('Согласовано ГИПом', 'Согласовано ГИПом'), ('Подготовка ответов', 'Подготовка ответов'), ('Подготовка ответов ГИПом', 'Подготовка ответов ГИПом'), ('Подготовка ответов руководителем', 'Подготовка ответов руководителем'), ('Подготовка ответов исполнителем', 'Подготовка ответов исполнителем'), ('Принято ГИПом', 'Принято ГИПом'), ('На согласовании Рецензентом', 'На согласовании Рецензентом'), ('Замечание снято', 'Замечание снято'), ('Закрыт', 'Закрыт')], verbose_name='Наименование структурного подразделения (отдела, службы,бюро,участка, группы)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
