# Generated by Django 3.2.14 on 2025-01-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0023_auto_20250124_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='num_reestrs',
            field=models.FloatField(default=0, verbose_name='Общее число реестров'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.customers', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='project_dogovor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.contracts', verbose_name='Договор №'),
        ),
        migrations.AlterField(
            model_name='reestinfo',
            name='project_reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.reviewers', verbose_name='Рецензент'),
        ),
    ]
