# Generated by Django 3.2.14 on 2025-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0024_auto_20250124_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='num_reestrs',
            field=models.IntegerField(default=0, verbose_name='Общее число реестров'),
        ),
    ]
