# Generated by Django 3.2.14 on 2025-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0027_auto_20250320_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestinfo',
            name='reestr_index',
            field=models.TextField(blank=True, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='reestr',
            name='remark_index',
            field=models.TextField(blank=True, null=True, verbose_name='Идентификатор'),
        ),
    ]
