# Generated by Django 3.2.14 on 2025-04-17 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formapp', '0028_auto_20250320_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='substitute',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
