# Generated by Django 3.2.14 on 2025-07-17 09:18

from django.conf import settings
from django.db import migrations, models
import formapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formapp', '0029_departments_substitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='substitute',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL, verbose_name='Замещает'),
        ),
        migrations.AlterField(
            model_name='files',
            name='belong_to',
            field=models.TextField(blank=True, null=True, verbose_name='Принадлежность'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=formapp.models.user_directory_path, verbose_name='Файл (общий объём загружаемых файлов не должен превышать 30 МБ)'),
        ),
    ]
