# Generated by Django 3.2.14 on 2024-09-03 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Таблица')),
                ('record_id', models.CharField(max_length=255, null=True, verbose_name='Объект')),
                ('action_on_model', models.CharField(choices=[('создал(а)', 'Создание'), ('изменил(а)', 'Изменение'), ('удалил(а)', 'Удаление')], max_length=50, null=True, verbose_name='Действие')),
                ('data', models.JSONField(default=dict, verbose_name='Изменяемые данные модели')),
                ('ipaddress', models.CharField(max_length=15, null=True, verbose_name='IP адресс')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
            ],
            options={
                'verbose_name': 'действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ('changed',),
            },
        ),
    ]
