# Generated by Django 3.2.14 on 2024-12-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('-changed',), 'verbose_name': 'действие пользователя', 'verbose_name_plural': 'Действия пользователей'},
        ),
    ]
