# Generated by Django 3.2.14 on 2025-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_alter_changelog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='object_id',
            field=models.IntegerField(default=0, verbose_name='ID объекта'),
            preserve_default=False,
        ),
    ]
