# Generated by Django 3.2.14 on 2025-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0003_changelog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/время изменения'),
        ),
    ]
